# Generated by Django 5.2.8 on 2025-12-01 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(help_text='Name of the vendor', max_length=255)),
                ('address', models.TextField(blank=True, help_text="Vendor's address", null=True)),
                ('phone_number', models.CharField(blank=True, help_text="Vendor's phone number", max_length=20, null=True)),
                ('email_address', models.EmailField(blank=True, help_text="Vendor's email address", max_length=254, null=True)),
                ('website', models.URLField(blank=True, help_text="Vendor's website URL", null=True)),
                ('primary_contact_name', models.CharField(blank=True, help_text='Name of the primary contact person', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='The user who owns this vendor', on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
                'db_table': 'vendors',
                'ordering': ['-created_at'],
            },
        ),
    ]
